title: Lisa's CTF Blog
description: Public CTF write-ups, cybersecurity learning, and web exploitation notes
author: Lisa Ho

remote_theme: pages-themes/hacker@v0.2.0

url: "https://lisaho0104.github.io"
baseurl: "/CTF"

markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

github_username: lisaho0104

lang: en
timezone: Australia/Melbourne