title: Lisa's CTF Blog
description: Public CTF write-ups, cybersecurity learning, and web exploitation notes
author: Lisa Ho

theme: jekyll-theme-hacker

url: "https://lisaho0104.github.io"
baseurl: "/CTF"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

github_username: lisaho0104

lang: en
timezone: Australia/Melbourne